### PR TITLE
Do not update the domNode property if it already has the correct value

### LINKED ISSUE #48: input cursor jumps to the end
The cursor will jump to the end of an input when changing the value in the middle.

This started happening in v0.9.0

### PR DESCRIPTION
**Pull request by lloiser**
fixes #48

### CODE REVIEW

**Comment by nathansobo** [comment]
I'm a bit worried about doing this across the board. Do we have a sense of what the overhead is of checking this on every property? I'd be more comfortable limiting it to specific properties such as input values.

**Comment by lloiser** [comment]
Here is what virtual-dom does: [virtual-hyperscript/index.js#L43-L61](https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/index.js#L43-L61)
It wraps the property with a special "hook" that is called whenever the property is going to be patched onto the dom node. see [vdom/apply-properties.js#L12-L18](https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/apply-properties.js#L12-L18)
This hook checks if the dom node already has the same value. see [virtual-hyperscript/hooks/soft-set-hook.js](https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/hooks/soft-set-hook.js)

**Comment by nathansobo** [comment]
Is that hook used for every property though? It would be good to make a list of tag names / property values that could change outside of the patch operation and limit this check to that.

**Comment by nathansobo** [comment]
Sorry... do we need an entire hooks system for this? I'd prefer to hard code this in the update logic and keep logic as simple as possible. The code you own ends up owning you.

**Comment by nathansobo** [comment]
Awesome. Thanks for fixing this!

**Comment by nathansobo** [comment]
If the list of element/property pairs we want to "soft set" grows I could see using a constant set to look them up or something, but I like the simplicity of this for now.

**Comment by UziTech** [comment]
@lloiser @nathansobo Thank you I can finally move off of v0.8.0 once this is released

**Comment by nathansobo** [comment]
Published in `etch@0.12.1`

**Pull request merged**
