### PR TITLE
Every project needs a logo

### PR DESCRIPTION
**Pull request by BinaryMuse**
Logo

Closes #https://github.com/github/atom-log/issues/415

### CODE REVIEW

**Comment by simurai** [comment]
Replaced with:

etch-96-48

Sorry, @BinaryMuse and R.I.P. "Etch A Sketch"

**Comment by thomasjo** [comment]
I ❤️ the new logo!

**Comment by BinaryMuse** [comment]
No apology necessary, @simurai! There is a reason I am a developer and not a designer. :)

**Comment by nathansobo** [comment]
⚡ 💥

**Pull request merged**
