### PR TITLE
Implement tests on Travis

### LINKED ISSUE #22: Get tests running on Travis
Travis doesn't seem to want to run `electron-mocha` correctly; even with failing tests checked in, the command produces no output and Travis says that the script exited with code 0.

### PR DESCRIPTION
**Pull request by BinaryMuse**
Fixes #22

### CODE REVIEW

**Comment by nathansobo** [comment]
❤️ ❤️ ❤️

**Comment by BinaryMuse** [comment]
Don't ❤️ yet it's not working haha

**Comment by nathansobo** [comment]
Yeah but you're trying. That's worth at least 3.

**Comment by BinaryMuse** [comment]
xvfb was the secret ingredient

**Pull request merged**
